version: '3.7'

services: 
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: hello
      - MYSQL_DATABASE: reddit
    volumes:
      - ./reddit.sql:/docker-entrypoint-initdb.d/reddit.sql
    ports:  
      - 3309:3306

reddit-frontend:
    container_name: reddit
    depends_on:
      - mariadb
    image: kamilla525/kovacsnorakamilla:reddit2
    restart: always
    ports:
      - 4040:4040
<<<<<<< HEAD
    network_mode: "host"
=======
    network_mode: "host"
    
>>>>>>> 325eea09d0ac9d8418bb7d1309c70c8fad41780f
